import { describe, expect, test } from "vitest";

import {
  buildBotOnlyBaselineAggregateReport,
  mergeBotOnlyBaselineAggregateReports,
  type BotOnlyBaselineAggregateReport,
  type BotOnlyBaselineMatchSummary,
} from "./bot-balance-baseline-aggregate";

describe("mergeBotOnlyBaselineAggregateReports", () => {
  test("combines chunk aggregates into one report", () => {
    const sharedMetadata = {
      mode: "fast-parity",
      timeScale: 0.02,
      timings: {
        readyAutoStartMs: 500,
        prepDurationMs: 900,
        battleDurationMs: 800,
        settleDurationMs: 200,
        eliminationDurationMs: 150,
        selectionTimeoutMs: 400,
      },
    } as const;
    const chunkA: BotOnlyBaselineAggregateReport = {
      metadata: sharedMetadata,
      requestedMatchCount: 2,
      completedMatches: 2,
      abortedMatches: 0,
      bossWins: 2,
      raidWins: 0,
      bossWinRate: 1,
      raidWinRate: 0,
      averageRounds: 10,
      minRounds: 9,
      maxRounds: 11,
      averageRemainingRaidPlayers: 0.5,
      battleMetrics: {
        totalBattles: 2,
        averageBossSurvivorsAtBattleEnd: 1,
        averageRaidSurvivorsAtBattleEnd: 0.5,
        bothSidesSurvivedRate: 0.5,
        bossWipedRate: 0,
        raidWipedRate: 0.5,
        endReasonCounts: {
          annihilation: 1,
          mutual_annihilation: 0,
          timeout_hp_lead: 1,
          timeout_hp_tie: 0,
          forced: 0,
          unexpected: 0,
        },
      },
      roundHistogram: { "9": 1, "11": 1 },
      playerMetrics: {
        P1: {
          averagePlacement: 1,
          firstPlaceRate: 1,
          averageRemainingHp: 100,
          averageRemainingLives: 0,
          averageFinalGold: 4,
          averageGoldEarned: 1,
          averageGoldSpent: 9,
          averagePurchaseCount: 3,
          averageRefreshCount: 2,
          averageSellCount: 1,
        },
      },
      bossBattleUnitMetrics: [{
        unitId: "patchouli",
        unitType: "mage",
        unitName: "パチュリー・ノーレッジ",
        battleAppearances: 2,
        matchesPresent: 2,
        averageunitLevel: 1.5,
        averageDamagePerBattle: 350,
        averageDamagePerMatch: 350,
        activeBattleRate: 1,
        averageAttackCountPerBattle: 3,
        averageHitCountPerBattle: 2,
        averageDamageTakenPerBattle: 120,
        averageFirstAttackMs: 140,
        averageLifetimeMs: 780,
        zeroDamageBattleRate: 0,
        survivalRate: 1,
        ownerWinRate: 1,
        adoptionRate: 1,
      }],
      raidBattleUnitMetrics: [{
        unitId: "yoshika",
        unitType: "yoshika",
        unitName: "宮古芳香",
        battleAppearances: 4,
        matchesPresent: 2,
        averageunitLevel: 1.25,
        averageDamagePerBattle: 200,
        averageDamagePerMatch: 400,
        activeBattleRate: 0.75,
        averageAttackCountPerBattle: 1.5,
        averageHitCountPerBattle: 1,
        averageDamageTakenPerBattle: 200,
        averageFirstAttackMs: 220,
        averageLifetimeMs: 500,
        zeroDamageBattleRate: 0.25,
        survivalRate: 0.5,
        ownerWinRate: 0.25,
        adoptionRate: 1,
        subUnitBattleAppearances: 1,
        subUnitMatchesPresent: 1,
        subUnitAdoptionRate: 0.5,
      }],
      finalBoardUnitMetrics: [{
        unitId: "yoshika",
        unitType: "yoshika",
        unitName: "宮古芳香",
        totalCopies: 3,
        matchesPresent: 2,
        averageCopiesPerMatch: 1.5,
        adoptionRate: 1,
      }],
      topDamageUnits: [{
        unitId: "unit-yoshika",
        unitName: "宮古芳香",
        side: "raid",
        totalDamage: 800,
        appearances: 2,
        averageDamagePerMatch: 400,
      }],
      highCostSummary: {
        offerObservationCount: 3,
        offerMatchCount: 2,
        purchaseCount: 1,
        purchaseMatchCount: 1,
        finalBoardCopies: 1,
        finalBoardMatchCount: 1,
        finalBoardAdoptionRate: 0.5,
      },
      highCostOfferMetrics: [{
        unitId: "junko",
        unitName: "純狐",
        unitType: "vanguard",
        role: "raid",
        source: "shop",
        cost: 4,
        observationCount: 3,
        matchesPresent: 2,
        offeredMatchRate: 1,
      }],
      rangeDamageEfficiencyMetrics: [{
        side: "raid",
        rangeBand: "range_1",
        battleAppearances: 4,
        totalDamage: 800,
        totalTheoreticalBaseDamage: 1000,
        normalizedDamageEfficiency: 0.8,
        totalAttackCount: 8,
        totalTheoreticalAttackCount: 10,
        attackOpportunityUtilization: 0.8,
        averageDamagePerBattle: 200,
        averageFirstAttackMs: 220,
        firstAttackSamples: 4,
        zeroDamageBattleRate: 0.25,
      }],
      rangeActionDiagnosticsMetrics: [{
        side: "raid",
        rangeBand: "range_1",
        battleAppearances: 4,
        movedBattleRate: 0.5,
        averageMoveCountPerBattle: 1.5,
        averageFirstMoveMs: 120,
        firstMoveSamples: 2,
        averageMoveToFirstAttackMs: 80,
        moveToFirstAttackSamples: 2,
        repositionBattleRate: 0.25,
        averageRepositionMoveCountPerBattle: 0.5,
        reachedAttackRangeBattleRate: 0.75,
        noAttackDespiteReachingRangeBattleRate: 0.25,
        noAttackWithoutReachingRangeBattleRate: 0,
        averageInitialNearestEnemyDistance: 4,
        averageBestNearestEnemyDistance: 1.5,
        averageDistanceClosed: 2.5,
        noAttackBattleRate: 0.25,
        movedNoAttackBattleRate: 0.25,
        attackedNoHitBattleRate: 0,
        lateSingleAttackBattleRate: 0.25,
        moveTargetDiagnosticSampleCount: 2,
        suboptimalMoveTargetRate: 0.5,
        averageExcessApproachSteps: 1.5,
        averageOutsideAttackRangeBeforeFirstAttackMs: 180,
        averageInAttackRangeBeforeFirstAttackMs: 90,
        averageAfterFirstAttackMs: 320,
        averageFirstReachedAttackRangeAtMs: 160,
        firstReachedAttackRangeSamples: 3,
        averageLeftLateralMovesPerBattle: 0,
        averageRightLateralMovesPerBattle: 0,
        firstLateralMoveLeftRate: null,
        firstLateralMoveRightRate: null,
        firstLateralMoveSamples: 0,
        sharedPursuitMoveSampleCount: 0,
        contestedPursuitMoveRate: null,
        plannedApproachGroupMoveSampleCount: 0,
        averagePlannedApproachGroupCompetitorCount: null,
        averagePlannedApproachGroupAssignedCount: null,
        oversubscribedPlannedApproachGroupRate: null,
        plannedApproachBattleCount: 0,
        plannedApproachMoveSampleCount: 0,
        plannedApproachStillOpenRate: null,
        usedPlannedApproachRate: null,
        plannedApproachPathBlockedRate: null,
        plannedApproachFirstAttackRate: null,
        plannedApproachMatchedFirstAttackTargetRate: null,
        plannedApproachReachedRangeWithoutAttackRate: null,
        plannedApproachNoReachNoAttackRate: null,
        plannedApproachNoAttackTargetDiedBeforeBattleEndRate: null,
        plannedApproachReachedRangeWithoutAttackWhileTargetAliveRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveRate: null,
        plannedApproachReachedRangeWithoutAttackWhileTargetAliveWithoutUsingPlannedDestinationRate: null,
        plannedApproachReachedRangeWithoutAttackWhileTargetAliveWithPathBlockedRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithoutUsingPlannedDestinationRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithPathBlockedRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithAllyAdjacentBlockRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithEnemyAdjacentBlockRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithMixedAdjacentBlockRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithRouteChokeBlockRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithAllyFrontierChokeRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithEnemyFrontierChokeRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithMixedFrontierChokeRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithUnclassifiedFrontierChokeRate: null,
      }],
      rangeFormationDiagnosticsMetrics: [{
        side: "raid",
        rangeBand: "range_1",
        battleAppearances: 4,
        frontAllyBlockedBattleRate: 0.5,
        averageFrontAllyCount: 0.5,
        averageInitialRow: 3.5,
        averageInitialColumn: 0.25,
        zeroDamageBattleRateWithFrontAlly: 0.5,
        zeroDamageBattleRateWithoutFrontAlly: 0,
        noAttackBattleRateWithFrontAlly: 0.5,
        noAttackBattleRateWithoutFrontAlly: 0,
      }],
    };
    const chunkB: BotOnlyBaselineAggregateReport = {
      metadata: sharedMetadata,
      requestedMatchCount: 3,
      completedMatches: 2,
      abortedMatches: 1,
      bossWins: 1,
      raidWins: 1,
      bossWinRate: 0.5,
      raidWinRate: 0.5,
      averageRounds: 12,
      minRounds: 12,
      maxRounds: 12,
      averageRemainingRaidPlayers: 1,
      battleMetrics: {
        totalBattles: 2,
        averageBossSurvivorsAtBattleEnd: 0.5,
        averageRaidSurvivorsAtBattleEnd: 1.5,
        bothSidesSurvivedRate: 1,
        bossWipedRate: 0.5,
        raidWipedRate: 0,
        endReasonCounts: {
          annihilation: 0,
          mutual_annihilation: 0,
          timeout_hp_lead: 1,
          timeout_hp_tie: 1,
          forced: 0,
          unexpected: 0,
        },
      },
      roundHistogram: { "12": 2 },
      playerMetrics: {
        P1: {
          averagePlacement: 1.5,
          firstPlaceRate: 0.5,
          averageRemainingHp: 80,
          averageRemainingLives: 0,
          averageFinalGold: 6,
          averageGoldEarned: 2,
          averageGoldSpent: 7,
          averagePurchaseCount: 2,
          averageRefreshCount: 1,
          averageSellCount: 0.5,
        },
      },
      bossBattleUnitMetrics: [{
        unitId: "patchouli",
        unitType: "mage",
        unitName: "パチュリー・ノーレッジ",
        battleAppearances: 1,
        matchesPresent: 1,
        averageunitLevel: 2,
        averageDamagePerBattle: 450,
        averageDamagePerMatch: 450,
        activeBattleRate: 1,
        averageAttackCountPerBattle: 4,
        averageHitCountPerBattle: 3,
        averageDamageTakenPerBattle: 100,
        averageFirstAttackMs: 100,
        averageLifetimeMs: 800,
        zeroDamageBattleRate: 0,
        survivalRate: 1,
        ownerWinRate: 1,
        adoptionRate: 0.5,
      }],
      raidBattleUnitMetrics: [{
        unitId: "yoshika",
        unitType: "yoshika",
        unitName: "宮古芳香",
        battleAppearances: 2,
        matchesPresent: 1,
        averageunitLevel: 2,
        averageDamagePerBattle: 500,
        averageDamagePerMatch: 500,
        activeBattleRate: 1,
        averageAttackCountPerBattle: 2,
        averageHitCountPerBattle: 1.5,
        averageDamageTakenPerBattle: 150,
        averageFirstAttackMs: 180,
        averageLifetimeMs: 650,
        zeroDamageBattleRate: 0,
        survivalRate: 1,
        ownerWinRate: 0.5,
        adoptionRate: 0.5,
        subUnitBattleAppearances: 1,
        subUnitMatchesPresent: 1,
        subUnitAdoptionRate: 0.5,
      }],
      finalBoardUnitMetrics: [{
        unitId: "yoshika",
        unitType: "yoshika",
        unitName: "宮古芳香",
        totalCopies: 1,
        matchesPresent: 1,
        averageCopiesPerMatch: 0.5,
        adoptionRate: 0.5,
      }],
      topDamageUnits: [{
        unitId: "unit-yoshika",
        unitName: "宮古芳香",
        side: "raid",
        totalDamage: 1000,
        appearances: 1,
        averageDamagePerMatch: 500,
      }],
      highCostSummary: {
        offerObservationCount: 1,
        offerMatchCount: 1,
        purchaseCount: 1,
        purchaseMatchCount: 1,
        finalBoardCopies: 1,
        finalBoardMatchCount: 1,
        finalBoardAdoptionRate: 0.5,
      },
      highCostOfferMetrics: [{
        unitId: "junko",
        unitName: "純狐",
        unitType: "vanguard",
        role: "raid",
        source: "shop",
        cost: 4,
        observationCount: 1,
        matchesPresent: 1,
        offeredMatchRate: 0.5,
      }],
      rangeDamageEfficiencyMetrics: [{
        side: "raid",
        rangeBand: "range_1",
        battleAppearances: 2,
        totalDamage: 1000,
        totalTheoreticalBaseDamage: 800,
        normalizedDamageEfficiency: 1.25,
        totalAttackCount: 4,
        totalTheoreticalAttackCount: 5,
        attackOpportunityUtilization: 0.8,
        averageDamagePerBattle: 500,
        averageFirstAttackMs: 180,
        firstAttackSamples: 2,
        zeroDamageBattleRate: 0,
      }],
      rangeActionDiagnosticsMetrics: [{
        side: "raid",
        rangeBand: "range_1",
        battleAppearances: 2,
        movedBattleRate: 1,
        averageMoveCountPerBattle: 2,
        averageFirstMoveMs: 100,
        firstMoveSamples: 2,
        averageMoveToFirstAttackMs: 60,
        moveToFirstAttackSamples: 2,
        repositionBattleRate: 0.5,
        averageRepositionMoveCountPerBattle: 1,
        reachedAttackRangeBattleRate: 1,
        noAttackDespiteReachingRangeBattleRate: 0,
        noAttackWithoutReachingRangeBattleRate: 0,
        averageInitialNearestEnemyDistance: 3,
        averageBestNearestEnemyDistance: 1,
        averageDistanceClosed: 2,
        noAttackBattleRate: 0,
        movedNoAttackBattleRate: 0,
        attackedNoHitBattleRate: 0,
        lateSingleAttackBattleRate: 0.5,
        moveTargetDiagnosticSampleCount: 1,
        suboptimalMoveTargetRate: 0,
        averageExcessApproachSteps: 0,
        averageOutsideAttackRangeBeforeFirstAttackMs: 120,
        averageInAttackRangeBeforeFirstAttackMs: 60,
        averageAfterFirstAttackMs: 280,
        averageFirstReachedAttackRangeAtMs: 100,
        firstReachedAttackRangeSamples: 2,
        averageLeftLateralMovesPerBattle: 0,
        averageRightLateralMovesPerBattle: 0,
        firstLateralMoveLeftRate: null,
        firstLateralMoveRightRate: null,
        firstLateralMoveSamples: 0,
        sharedPursuitMoveSampleCount: 0,
        contestedPursuitMoveRate: null,
        plannedApproachGroupMoveSampleCount: 0,
        averagePlannedApproachGroupCompetitorCount: null,
        averagePlannedApproachGroupAssignedCount: null,
        oversubscribedPlannedApproachGroupRate: null,
        plannedApproachBattleCount: 0,
        plannedApproachMoveSampleCount: 0,
        plannedApproachStillOpenRate: null,
        usedPlannedApproachRate: null,
        plannedApproachPathBlockedRate: null,
        plannedApproachFirstAttackRate: null,
        plannedApproachMatchedFirstAttackTargetRate: null,
        plannedApproachReachedRangeWithoutAttackRate: null,
        plannedApproachNoReachNoAttackRate: null,
        plannedApproachNoAttackTargetDiedBeforeBattleEndRate: null,
        plannedApproachReachedRangeWithoutAttackWhileTargetAliveRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveRate: null,
        plannedApproachReachedRangeWithoutAttackWhileTargetAliveWithoutUsingPlannedDestinationRate: null,
        plannedApproachReachedRangeWithoutAttackWhileTargetAliveWithPathBlockedRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithoutUsingPlannedDestinationRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithPathBlockedRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithAllyAdjacentBlockRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithEnemyAdjacentBlockRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithMixedAdjacentBlockRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithRouteChokeBlockRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithAllyFrontierChokeRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithEnemyFrontierChokeRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithMixedFrontierChokeRate: null,
        plannedApproachNoReachNoAttackWhileTargetAliveWithUnclassifiedFrontierChokeRate: null,
      }],
      rangeFormationDiagnosticsMetrics: [{
        side: "raid",
        rangeBand: "range_1",
        battleAppearances: 2,
        frontAllyBlockedBattleRate: 0.5,
        averageFrontAllyCount: 0.5,
        averageInitialRow: 4,
        averageInitialColumn: 0,
        zeroDamageBattleRateWithFrontAlly: 0,
        zeroDamageBattleRateWithoutFrontAlly: 0,
        noAttackBattleRateWithFrontAlly: 0,
        noAttackBattleRateWithoutFrontAlly: 0,
      }],
    };

    const merged = mergeBotOnlyBaselineAggregateReports([chunkA, chunkB]);

    expect(merged.requestedMatchCount).toBe(5);
    expect(merged.completedMatches).toBe(4);
    expect(merged.abortedMatches).toBe(1);
    expect(merged.bossWins).toBe(3);
    expect(merged.raidWins).toBe(1);
    expect(merged.averageRounds).toBe(11);
    expect(merged.minRounds).toBe(9);
    expect(merged.maxRounds).toBe(12);
    expect(merged.battleMetrics).toEqual({
      totalBattles: 4,
      averageBossSurvivorsAtBattleEnd: 0.75,
      averageRaidSurvivorsAtBattleEnd: 1,
      bothSidesSurvivedRate: 0.75,
      bossWipedRate: 0.25,
      raidWipedRate: 0.25,
      endReasonCounts: {
        annihilation: 1,
        mutual_annihilation: 0,
        timeout_hp_lead: 2,
        timeout_hp_tie: 1,
        forced: 0,
        unexpected: 0,
      },
    });
    expect(merged.roundHistogram).toEqual({
      "9": 1,
      "11": 1,
      "12": 2,
    });
    expect(merged.playerMetrics.P1?.averagePlacement).toBeCloseTo(1.25);
    expect(merged.playerMetrics.P1?.firstPlaceRate).toBeCloseTo(0.75);
    expect(merged.playerMetrics.P1?.averageRemainingHp).toBeCloseTo(90);
    expect(merged.playerMetrics.P1?.averageFinalGold).toBeCloseTo(5);
    expect(merged.playerMetrics.P1?.averageGoldEarned).toBeCloseTo(1.5);
    expect(merged.playerMetrics.P1?.averageGoldSpent).toBeCloseTo(8);
    expect(merged.playerMetrics.P1?.averagePurchaseCount).toBeCloseTo(2.5);
    expect(merged.playerMetrics.P1?.averageRefreshCount).toBeCloseTo(1.5);
    expect(merged.playerMetrics.P1?.averageSellCount).toBeCloseTo(0.75);
    expect(merged.bossBattleUnitMetrics).toEqual([
      expect.objectContaining({
        unitId: "patchouli",
        battleAppearances: 3,
        matchesPresent: 3,
        averageunitLevel: (2 * 1.5 + 1 * 2) / 3,
        averageDamagePerBattle: (2 * 350 + 1 * 450) / 3,
        averageDamagePerMatch: 287.5,
        activeBattleRate: 1,
        averageAttackCountPerBattle: (2 * 3 + 4) / 3,
        averageHitCountPerBattle: (2 * 2 + 3) / 3,
        averageDamageTakenPerBattle: (2 * 120 + 100) / 3,
        averageFirstAttackMs: (2 * 140 + 100) / 3,
        averageLifetimeMs: (2 * 780 + 800) / 3,
        zeroDamageBattleRate: 0,
        survivalRate: 1,
        ownerWinRate: 1,
        adoptionRate: 3 / 4,
      }),
    ]);
    expect(merged.raidBattleUnitMetrics).toEqual([
      expect.objectContaining({
        unitId: "yoshika",
        unitType: "yoshika",
        battleAppearances: 6,
        matchesPresent: 3,
        averageunitLevel: (4 * 1.25 + 2 * 2) / 6,
        averageDamagePerBattle: 300,
        averageDamagePerMatch: 450,
        activeBattleRate: 5 / 6,
        averageAttackCountPerBattle: 10 / 6,
        averageHitCountPerBattle: 7 / 6,
        averageDamageTakenPerBattle: 1100 / 6,
        averageFirstAttackMs: 1020 / 5,
        averageLifetimeMs: 3300 / 6,
        zeroDamageBattleRate: 1 / 6,
        survivalRate: 4 / 6,
        ownerWinRate: 2 / 6,
        adoptionRate: 3 / 4,
        subUnitBattleAppearances: 2,
        subUnitMatchesPresent: 2,
        subUnitAdoptionRate: 0.5,
      }),
    ]);
    expect(merged.finalBoardUnitMetrics).toEqual([
      expect.objectContaining({
        unitId: "yoshika",
        unitType: "yoshika",
        totalCopies: 4,
        matchesPresent: 3,
        averageCopiesPerMatch: 1,
        adoptionRate: 3 / 4,
      }),
    ]);
    expect(merged.topDamageUnits).toEqual([
      expect.objectContaining({
        unitId: "unit-yoshika",
        totalDamage: 1800,
        appearances: 3,
        averageDamagePerMatch: 450,
      }),
    ]);
    expect(merged.highCostSummary).toEqual({
      offerObservationCount: 4,
      offerMatchCount: 3,
      purchaseCount: 2,
      purchaseMatchCount: 2,
      finalBoardCopies: 2,
      finalBoardMatchCount: 2,
      finalBoardAdoptionRate: 0.5,
    });
    expect(merged.highCostOfferMetrics).toEqual([
      expect.objectContaining({
        unitId: "junko",
        observationCount: 4,
        matchesPresent: 3,
        offeredMatchRate: 0.75,
      }),
    ]);
    expect(merged.rangeDamageEfficiencyMetrics).toEqual([
      expect.objectContaining({
        side: "raid",
        rangeBand: "range_1",
        battleAppearances: 6,
        totalDamage: 1800,
        totalTheoreticalBaseDamage: 1800,
        normalizedDamageEfficiency: 1,
        totalAttackCount: 12,
        totalTheoreticalAttackCount: 15,
        attackOpportunityUtilization: 0.8,
        averageDamagePerBattle: 300,
        averageFirstAttackMs: (220 * 4 + 180 * 2) / 6,
        zeroDamageBattleRate: 1 / 6,
      }),
    ]);
    expect(merged.rangeActionDiagnosticsMetrics).toEqual([
      expect.objectContaining({
        side: "raid",
        rangeBand: "range_1",
        battleAppearances: 6,
        movedBattleRate: 4 / 6,
        averageMoveCountPerBattle: 5 / 3,
        averageFirstMoveMs: 110,
        firstMoveSamples: 4,
        averageMoveToFirstAttackMs: 70,
        moveToFirstAttackSamples: 4,
        repositionBattleRate: 2 / 6,
        averageRepositionMoveCountPerBattle: 2 / 3,
        reachedAttackRangeBattleRate: 5 / 6,
        noAttackDespiteReachingRangeBattleRate: 1 / 6,
        noAttackWithoutReachingRangeBattleRate: 0,
        averageInitialNearestEnemyDistance: 11 / 3,
        averageBestNearestEnemyDistance: 4 / 3,
        averageDistanceClosed: 7 / 3,
        noAttackBattleRate: 1 / 6,
        movedNoAttackBattleRate: 1 / 6,
        attackedNoHitBattleRate: 0,
        lateSingleAttackBattleRate: 1 / 3,
        moveTargetDiagnosticSampleCount: 3,
        suboptimalMoveTargetRate: 1 / 3,
        averageExcessApproachSteps: 1,
        averageOutsideAttackRangeBeforeFirstAttackMs: 160,
        averageInAttackRangeBeforeFirstAttackMs: 80,
        averageAfterFirstAttackMs: 920 / 3,
        averageFirstReachedAttackRangeAtMs: 136,
        firstReachedAttackRangeSamples: 5,
      }),
    ]);
    expect(merged.rangeFormationDiagnosticsMetrics).toEqual([
      expect.objectContaining({
        side: "raid",
        rangeBand: "range_1",
        battleAppearances: 6,
        frontAllyBlockedBattleRate: 0.5,
        averageFrontAllyCount: 0.5,
        averageInitialRow: (4 * 3.5 + 2 * 4) / 6,
        averageInitialColumn: 1 / 6,
        zeroDamageBattleRateWithFrontAlly: 1 / 3,
        zeroDamageBattleRateWithoutFrontAlly: 0,
        noAttackBattleRateWithFrontAlly: 1 / 3,
        noAttackBattleRateWithoutFrontAlly: 0,
      }),
    ]);
  });

  test("drops metadata when chunk conditions differ", () => {
    const merged = mergeBotOnlyBaselineAggregateReports([
      {
        requestedMatchCount: 1,
        completedMatches: 1,
        abortedMatches: 0,
        bossWins: 1,
        raidWins: 0,
        bossWinRate: 1,
        raidWinRate: 0,
        averageRounds: 10,
        minRounds: 10,
        maxRounds: 10,
        averageRemainingRaidPlayers: 0,
        battleMetrics: {
          totalBattles: 0,
          averageBossSurvivorsAtBattleEnd: 0,
          averageRaidSurvivorsAtBattleEnd: 0,
          bothSidesSurvivedRate: 0,
          bossWipedRate: 0,
          raidWipedRate: 0,
          endReasonCounts: {
            annihilation: 0,
            mutual_annihilation: 0,
            timeout_hp_lead: 0,
            timeout_hp_tie: 0,
            forced: 0,
            unexpected: 0,
          },
        },
        roundHistogram: { "10": 1 },
        playerMetrics: {},
        bossBattleUnitMetrics: [],
        raidBattleUnitMetrics: [],
        finalBoardUnitMetrics: [],
        topDamageUnits: [],
        highCostSummary: {
          offerObservationCount: 0,
          offerMatchCount: 0,
          purchaseCount: 0,
          purchaseMatchCount: 0,
          finalBoardCopies: 0,
          finalBoardMatchCount: 0,
          finalBoardAdoptionRate: 0,
        },
        highCostOfferMetrics: [],
        rangeDamageEfficiencyMetrics: [],
        rangeActionDiagnosticsMetrics: [],
        rangeFormationDiagnosticsMetrics: [],
        metadata: {
          mode: "fast-parity",
          timeScale: 0.02,
          timings: {
            readyAutoStartMs: 500,
            prepDurationMs: 900,
            battleDurationMs: 800,
            settleDurationMs: 200,
            eliminationDurationMs: 150,
            selectionTimeoutMs: 400,
          },
        },
      },
      {
        requestedMatchCount: 1,
        completedMatches: 1,
        abortedMatches: 0,
        bossWins: 1,
        raidWins: 0,
        bossWinRate: 1,
        raidWinRate: 0,
        averageRounds: 10,
        minRounds: 10,
        maxRounds: 10,
        averageRemainingRaidPlayers: 0,
        battleMetrics: {
          totalBattles: 0,
          averageBossSurvivorsAtBattleEnd: 0,
          averageRaidSurvivorsAtBattleEnd: 0,
          bothSidesSurvivedRate: 0,
          bossWipedRate: 0,
          raidWipedRate: 0,
          endReasonCounts: {
            annihilation: 0,
            mutual_annihilation: 0,
            timeout_hp_lead: 0,
            timeout_hp_tie: 0,
            forced: 0,
            unexpected: 0,
          },
        },
        roundHistogram: { "10": 1 },
        playerMetrics: {},
        bossBattleUnitMetrics: [],
        raidBattleUnitMetrics: [],
        finalBoardUnitMetrics: [],
        topDamageUnits: [],
        highCostSummary: {
          offerObservationCount: 0,
          offerMatchCount: 0,
          purchaseCount: 0,
          purchaseMatchCount: 0,
          finalBoardCopies: 0,
          finalBoardMatchCount: 0,
          finalBoardAdoptionRate: 0,
        },
        highCostOfferMetrics: [],
        rangeDamageEfficiencyMetrics: [],
        rangeActionDiagnosticsMetrics: [],
        rangeFormationDiagnosticsMetrics: [],
        metadata: {
          mode: "real-play",
          timeScale: 1,
          timings: {
            readyAutoStartMs: 2_000,
            prepDurationMs: 45_000,
            battleDurationMs: 40_000,
            settleDurationMs: 1_500,
            eliminationDurationMs: 1_500,
            selectionTimeoutMs: 30_000,
          },
        },
      },
    ]);

    expect(merged.metadata).toBeUndefined();
  });
});

describe("buildBotOnlyBaselineAggregateReport", () => {
  test("summarizes lean bot-only match results", () => {
    const aggregate = buildBotOnlyBaselineAggregateReport([
      {
        metadata: {
          mode: "fast-parity",
          timeScale: 0.02,
          timings: {
            readyAutoStartMs: 500,
            prepDurationMs: 900,
            battleDurationMs: 800,
            settleDurationMs: 200,
            eliminationDurationMs: 150,
            selectionTimeoutMs: 400,
          },
        },
        totalRounds: 3,
        bossPlayerId: "boss-1",
        ranking: ["boss-1", "raid-a", "raid-b", "raid-c"],
        playerLabels: {},
        finalPlayers: [
          {
            playerId: "boss-1",
            label: "P1",
            role: "boss",
            hp: 100,
            gold: 8,
            remainingLives: 0,
            eliminated: false,
            rank: 1,
            selectedHeroId: "",
            selectedBossId: "remilia",
            totalGoldEarned: 2,
            totalGoldSpent: 11,
            purchaseCount: 4,
            refreshCount: 3,
            sellCount: 1,
            boardUnits: [{
              cell: 0,
              unitName: "レミリア",
              unitType: "remilia",
              unitId: "unit-remilia-1",
              unitLevel: 1,
              subUnitName: "",
            }],
          },
          {
            playerId: "raid-a",
            label: "P2",
            role: "raid",
            hp: 100,
            gold: 3,
            remainingLives: 0,
            eliminated: true,
            rank: 2,
            selectedHeroId: "reimu",
            selectedBossId: "",
            totalGoldEarned: 1,
            totalGoldSpent: 12,
            purchaseCount: 5,
            refreshCount: 2,
            sellCount: 1,
            boardUnits: [{
              cell: 1,
              unitName: "博麗霊夢",
              unitType: "reimu",
              unitId: "unit-reimu-1",
              unitLevel: 1,
              subUnitName: "",
            }],
          },
          {
            playerId: "raid-b",
            label: "P3",
            role: "raid",
            hp: 80,
            gold: 6,
            remainingLives: 1,
            eliminated: false,
            rank: 3,
            selectedHeroId: "",
            selectedBossId: "",
            totalGoldEarned: 0,
            totalGoldSpent: 7,
            purchaseCount: 2,
            refreshCount: 1,
            sellCount: 0,
            boardUnits: [],
          },
          {
            playerId: "raid-c",
            label: "P4",
            role: "raid",
            hp: 0,
            gold: 1,
            remainingLives: 0,
            eliminated: true,
            rank: 4,
            selectedHeroId: "",
            selectedBossId: "",
            totalGoldEarned: 3,
            totalGoldSpent: 10,
            purchaseCount: 3,
            refreshCount: 4,
            sellCount: 2,
            boardUnits: [],
          },
        ],
        battles: [{
          leftPlayerId: "boss-1",
          rightPlayerId: "raid-a",
          winner: "left",
          battleEndReason: "annihilation",
          bossSurvivors: 1,
          raidSurvivors: 0,
          unitDamageBreakdown: [{
            playerId: "boss-1",
            label: "P1",
            unitId: "unit-remilia-1",
            unitName: "レミリア",
            side: "boss",
            totalDamage: 300,
          }],
          unitOutcomes: [{
            playerId: "boss-1",
            label: "P1",
            unitId: "unit-remilia-1",
            unitName: "レミリア",
            unitType: "remilia",
            side: "boss",
            totalDamage: 300,
            phaseContributionDamage: 0,
            finalHp: 500,
            alive: true,
            unitLevel: 1,
            subUnitName: "",
            isSpecialUnit: true,
            attackCount: 2,
            hitCount: 2,
            damageTaken: 80,
            moveCount: 2,
            firstMoveAtMs: 30,
            firstAttackAtMs: 90,
            repositionMoveCount: 1,
            initialNearestEnemyDistance: 5,
            bestNearestEnemyDistance: 1,
            lifetimeMs: 400,
            battleDurationMs: 500,
          }],
        }],
        purchases: [{
          playerId: "raid-a",
          label: "P2",
          actionType: "buy_unit",
          unitType: "vanguard",
          cost: 4,
        }],
        observedShopOffers: [{
          playerId: "raid-a",
          label: "P2",
          role: "raid",
          source: "shop",
          unitId: "junko",
          unitName: "純狐",
          unitType: "vanguard",
          cost: 4,
          observationCount: 2,
        }],
      } satisfies BotOnlyBaselineMatchSummary,
    ]);

    expect(aggregate.completedMatches).toBe(1);
    expect(aggregate.bossWins).toBe(1);
    expect(aggregate.averageRounds).toBe(3);
    expect(aggregate.battleMetrics).toEqual({
      totalBattles: 1,
      averageBossSurvivorsAtBattleEnd: 1,
      averageRaidSurvivorsAtBattleEnd: 0,
      bothSidesSurvivedRate: 0,
      bossWipedRate: 0,
      raidWipedRate: 1,
      endReasonCounts: {
        annihilation: 1,
        mutual_annihilation: 0,
        timeout_hp_lead: 0,
        timeout_hp_tie: 0,
        forced: 0,
        unexpected: 0,
      },
    });
    expect(aggregate.playerMetrics.P1?.averagePlacement).toBe(1);
    expect(aggregate.playerMetrics.P1?.averageFinalGold).toBe(8);
    expect(aggregate.playerMetrics.P1?.averageGoldEarned).toBe(2);
    expect(aggregate.playerMetrics.P1?.averageGoldSpent).toBe(11);
    expect(aggregate.playerMetrics.P1?.averagePurchaseCount).toBe(4);
    expect(aggregate.playerMetrics.P1?.averageRefreshCount).toBe(3);
    expect(aggregate.playerMetrics.P1?.averageSellCount).toBe(1);
    expect(aggregate.bossBattleUnitMetrics).toEqual([
      expect.objectContaining({
        unitId: "unit-remilia-1",
        unitType: "remilia",
        averageDamagePerBattle: 300,
        averageDamagePerMatch: 300,
        activeBattleRate: 1,
        averageAttackCountPerBattle: 2,
        averageHitCountPerBattle: 2,
        averageDamageTakenPerBattle: 80,
        averageFirstAttackMs: 90,
        averageLifetimeMs: 400,
        zeroDamageBattleRate: 0,
        ownerWinRate: 1,
        adoptionRate: 1,
      }),
    ]);
    expect(aggregate.raidBattleUnitMetrics).toEqual([]);
    expect(aggregate.finalBoardUnitMetrics).toEqual(expect.arrayContaining([
      expect.objectContaining({
        unitId: "unit-remilia-1",
        unitType: "remilia",
        totalCopies: 1,
        adoptionRate: 1,
      }),
      expect.objectContaining({
        unitId: "unit-reimu-1",
        unitType: "reimu",
        totalCopies: 1,
        adoptionRate: 1,
      }),
    ]));
    expect(aggregate.topDamageUnits).toEqual([
      expect.objectContaining({
        unitId: "unit-remilia-1",
        totalDamage: 300,
      }),
    ]);
    expect(aggregate.highCostSummary).toEqual({
      offerObservationCount: 2,
      offerMatchCount: 1,
      purchaseCount: 1,
      purchaseMatchCount: 1,
      finalBoardCopies: 0,
      finalBoardMatchCount: 0,
      finalBoardAdoptionRate: 0,
    });
    expect(aggregate.highCostOfferMetrics).toEqual([
      expect.objectContaining({
        unitId: "junko",
        unitName: "純狐",
        cost: 4,
        observationCount: 2,
        matchesPresent: 1,
        offeredMatchRate: 1,
      }),
    ]);
    expect(aggregate.rangeDamageEfficiencyMetrics).toHaveLength(1);
    expect(aggregate.rangeDamageEfficiencyMetrics[0]).toMatchObject({
      side: "boss",
      rangeBand: "range_2_plus",
      battleAppearances: 1,
      totalDamage: 300,
      totalAttackCount: 2,
      averageDamagePerBattle: 300,
      totalTheoreticalAttackCount: 0.57 * 0.4,
      attackOpportunityUtilization: 2 / (0.57 * 0.4),
      averageFirstAttackMs: 90,
      zeroDamageBattleRate: 0,
    });
    expect(aggregate.rangeDamageEfficiencyMetrics[0]?.totalTheoreticalBaseDamage).toBeCloseTo(47 * 0.57 * 0.4);
    expect(aggregate.rangeDamageEfficiencyMetrics[0]?.normalizedDamageEfficiency)
      .toBeCloseTo(300 / (47 * 0.57 * 0.4));
    expect(aggregate.rangeActionDiagnosticsMetrics).toEqual([
      expect.objectContaining({
        side: "boss",
        rangeBand: "range_2_plus",
        battleAppearances: 1,
        movedBattleRate: 1,
        averageMoveCountPerBattle: 2,
        averageFirstMoveMs: 30,
        firstMoveSamples: 1,
        averageMoveToFirstAttackMs: 60,
        moveToFirstAttackSamples: 1,
        repositionBattleRate: 1,
        averageRepositionMoveCountPerBattle: 1,
        reachedAttackRangeBattleRate: 1,
        noAttackDespiteReachingRangeBattleRate: 0,
        noAttackWithoutReachingRangeBattleRate: 0,
        averageInitialNearestEnemyDistance: 5,
        averageBestNearestEnemyDistance: 1,
        averageDistanceClosed: 4,
        noAttackBattleRate: 0,
        movedNoAttackBattleRate: 0,
        attackedNoHitBattleRate: 0,
        lateSingleAttackBattleRate: 0,
        moveTargetDiagnosticSampleCount: 0,
        suboptimalMoveTargetRate: null,
        averageExcessApproachSteps: null,
        averageOutsideAttackRangeBeforeFirstAttackMs: 0,
        averageInAttackRangeBeforeFirstAttackMs: 0,
        averageAfterFirstAttackMs: 0,
        averageFirstReachedAttackRangeAtMs: null,
        firstReachedAttackRangeSamples: 0,
      }),
    ]);
    expect(aggregate.rangeFormationDiagnosticsMetrics).toEqual([
      expect.objectContaining({
        side: "boss",
        rangeBand: "range_2_plus",
        battleAppearances: 1,
        frontAllyBlockedBattleRate: 0,
        averageFrontAllyCount: 0,
        averageInitialRow: null,
        averageInitialColumn: null,
        zeroDamageBattleRateWithFrontAlly: null,
        zeroDamageBattleRateWithoutFrontAlly: 0,
        noAttackBattleRateWithFrontAlly: null,
        noAttackBattleRateWithoutFrontAlly: 0,
      }),
    ]);
  });

  test("classifies melee failure patterns into no-contact, reached-range no-attack, and late single attack", () => {
    const aggregate = buildBotOnlyBaselineAggregateReport([{
      totalRounds: 1,
      bossPlayerId: "boss-1",
      ranking: ["boss-1", "raid-a", "raid-b", "raid-c"],
      playerLabels: {
        "boss-1": "P1",
        "raid-a": "P2",
        "raid-b": "P3",
        "raid-c": "P4",
      },
      finalPlayers: [
        {
          playerId: "boss-1",
          label: "P1",
          role: "boss",
          hp: 100,
          gold: 0,
          remainingLives: 0,
          eliminated: false,
          rank: 1,
          selectedHeroId: "",
          selectedBossId: "",
          totalGoldEarned: 0,
          totalGoldSpent: 0,
          purchaseCount: 0,
          refreshCount: 0,
          sellCount: 0,
          boardUnits: [],
        },
        {
          playerId: "raid-a",
          label: "P2",
          role: "raid",
          hp: 100,
          gold: 0,
          remainingLives: 2,
          eliminated: false,
          rank: 2,
          selectedHeroId: "",
          selectedBossId: "",
          totalGoldEarned: 0,
          totalGoldSpent: 0,
          purchaseCount: 0,
          refreshCount: 0,
          sellCount: 0,
          boardUnits: [],
        },
        {
          playerId: "raid-b",
          label: "P3",
          role: "raid",
          hp: 100,
          gold: 0,
          remainingLives: 2,
          eliminated: false,
          rank: 3,
          selectedHeroId: "",
          selectedBossId: "",
          totalGoldEarned: 0,
          totalGoldSpent: 0,
          purchaseCount: 0,
          refreshCount: 0,
          sellCount: 0,
          boardUnits: [],
        },
        {
          playerId: "raid-c",
          label: "P4",
          role: "raid",
          hp: 100,
          gold: 0,
          remainingLives: 2,
          eliminated: false,
          rank: 4,
          selectedHeroId: "",
          selectedBossId: "",
          totalGoldEarned: 0,
          totalGoldSpent: 0,
          purchaseCount: 0,
          refreshCount: 0,
          sellCount: 0,
          boardUnits: [],
        },
      ],
      battles: [{
        leftPlayerId: "boss-1",
        rightPlayerId: "raid-a",
        winner: "left",
        battleEndReason: "forced",
        bossSurvivors: 1,
        raidSurvivors: 3,
        unitDamageBreakdown: [],
        unitOutcomes: [
          {
            playerId: "raid-a",
            label: "P2",
            unitId: "yoshika",
            unitName: "宮古芳香",
            unitType: "yoshika",
            side: "raid",
            totalDamage: 0,
            phaseContributionDamage: 0,
            finalHp: 100,
            alive: true,
            unitLevel: 1,
            subUnitName: "",
            isSpecialUnit: false,
            attackCount: 0,
            hitCount: 0,
            damageTaken: 0,
            moveCount: 3,
            firstMoveAtMs: 0,
            firstAttackAtMs: null,
            repositionMoveCount: 0,
            lifetimeMs: 300,
            battleDurationMs: 300,
            initialNearestEnemyDistance: 4,
            bestNearestEnemyDistance: 2,
          },
          {
            playerId: "raid-b",
            label: "P3",
            unitId: "yoshika",
            unitName: "宮古芳香",
            unitType: "yoshika",
            side: "raid",
            totalDamage: 0,
            phaseContributionDamage: 0,
            finalHp: 100,
            alive: true,
            unitLevel: 1,
            subUnitName: "",
            isSpecialUnit: false,
            attackCount: 0,
            hitCount: 0,
            damageTaken: 0,
            moveCount: 2,
            firstMoveAtMs: 0,
            firstAttackAtMs: null,
            repositionMoveCount: 0,
            lifetimeMs: 300,
            battleDurationMs: 300,
            initialNearestEnemyDistance: 3,
            bestNearestEnemyDistance: 1,
          },
          {
            playerId: "raid-c",
            label: "P4",
            unitId: "yoshika",
            unitName: "宮古芳香",
            unitType: "yoshika",
            side: "raid",
            totalDamage: 40,
            phaseContributionDamage: 0,
            finalHp: 100,
            alive: true,
            unitLevel: 1,
            subUnitName: "",
            isSpecialUnit: false,
            attackCount: 1,
            hitCount: 1,
            damageTaken: 0,
            moveCount: 3,
            firstMoveAtMs: 0,
            firstAttackAtMs: 210,
            repositionMoveCount: 0,
            lifetimeMs: 300,
            battleDurationMs: 300,
            initialNearestEnemyDistance: 3,
            bestNearestEnemyDistance: 1,
          },
        ],
      }],
    }]);

    expect(aggregate.rangeActionDiagnosticsMetrics).toEqual([
      expect.objectContaining({
        side: "raid",
        rangeBand: "range_1",
        battleAppearances: 3,
        noAttackWithoutReachingRangeBattleRate: 1 / 3,
        noAttackDespiteReachingRangeBattleRate: 1 / 3,
        lateSingleAttackBattleRate: 1 / 3,
        moveTargetDiagnosticSampleCount: 0,
        suboptimalMoveTargetRate: null,
        averageExcessApproachSteps: null,
        averageOutsideAttackRangeBeforeFirstAttackMs: 0,
        averageInAttackRangeBeforeFirstAttackMs: 0,
        averageAfterFirstAttackMs: 0,
        averageFirstReachedAttackRangeAtMs: null,
        firstReachedAttackRangeSamples: 0,
      }),
    ]);
    expect(aggregate.rangeFormationDiagnosticsMetrics).toEqual([
      expect.objectContaining({
        side: "raid",
        rangeBand: "range_1",
        battleAppearances: 3,
        frontAllyBlockedBattleRate: 0,
        averageFrontAllyCount: 0,
        zeroDamageBattleRateWithFrontAlly: null,
        zeroDamageBattleRateWithoutFrontAlly: 2 / 3,
        noAttackBattleRateWithFrontAlly: null,
        noAttackBattleRateWithoutFrontAlly: 2 / 3,
      }),
    ]);
  });

  test("separates raid melee diagnostics into special and standard cohorts", () => {
    const aggregate = buildBotOnlyBaselineAggregateReport([{
      totalRounds: 1,
      bossPlayerId: "boss-1",
      ranking: ["boss-1", "raid-a", "raid-b", "raid-c"],
      playerLabels: {
        "boss-1": "P1",
        "raid-a": "P2",
        "raid-b": "P3",
        "raid-c": "P4",
      },
      finalPlayers: [
        {
          playerId: "boss-1",
          label: "P1",
          role: "boss",
          hp: 100,
          gold: 0,
          remainingLives: 1,
          eliminated: false,
          rank: 1,
          selectedHeroId: "",
          selectedBossId: "remilia",
          totalGoldEarned: 0,
          totalGoldSpent: 0,
          purchaseCount: 0,
          refreshCount: 0,
          sellCount: 0,
          boardUnits: [],
        },
        {
          playerId: "raid-a",
          label: "P2",
          role: "raid",
          hp: 100,
          gold: 0,
          remainingLives: 1,
          eliminated: false,
          rank: 2,
          selectedHeroId: "reimu",
          selectedBossId: "",
          totalGoldEarned: 0,
          totalGoldSpent: 0,
          purchaseCount: 0,
          refreshCount: 0,
          sellCount: 0,
          boardUnits: [],
        },
      ],
      battles: [{
        leftPlayerId: "raid-a",
        rightPlayerId: "boss-1",
        winner: "right",
        bossSurvivors: 1,
        raidSurvivors: 1,
        unitDamageBreakdown: [],
        unitOutcomes: [
          {
            playerId: "raid-a",
            label: "P2",
            unitId: "jyoon",
            unitName: "女苑",
            side: "raid",
            totalDamage: 10,
            phaseContributionDamage: 10,
            finalHp: 560,
            alive: true,
            unitLevel: 1,
            subUnitName: "",
            isSpecialUnit: true,
            attackCount: 1,
            hitCount: 1,
            damageTaken: 100,
            lifetimeMs: 3000,
            firstAttackAtMs: 900,
          },
          {
            playerId: "raid-a",
            label: "P2",
            unitId: "yoshika",
            unitName: "宮古芳香",
            side: "raid",
            totalDamage: 120,
            phaseContributionDamage: 120,
            finalHp: 0,
            alive: false,
            unitLevel: 1,
            subUnitName: "",
            isSpecialUnit: false,
            attackCount: 2,
            hitCount: 2,
            damageTaken: 300,
            lifetimeMs: 2000,
            firstAttackAtMs: 500,
          },
        ],
      }],
    }]);

    expect(aggregate.raidMeleeCohortMetrics).toEqual([
      {
        cohort: "special",
        battleAppearances: 1,
        averageDamagePerBattle: 10,
        averageAttackCountPerBattle: 1,
        averageFirstAttackMs: 900,
        averageLifetimeMs: 3000,
        zeroDamageBattleRate: 0,
        survivalRate: 1,
      },
      {
        cohort: "standard",
        battleAppearances: 1,
        averageDamagePerBattle: 120,
        averageAttackCountPerBattle: 2,
        averageFirstAttackMs: 500,
        averageLifetimeMs: 2000,
        zeroDamageBattleRate: 0,
        survivalRate: 0,
      },
    ]);
  });

  test("builds per-unit diagnostics for raid special melee units", () => {
    const aggregate = buildBotOnlyBaselineAggregateReport([{
      totalRounds: 1,
      bossPlayerId: "boss-1",
      ranking: ["boss-1", "raid-a", "raid-b", "raid-c"],
      playerLabels: {
        "boss-1": "P1",
        "raid-a": "P2",
        "raid-b": "P3",
        "raid-c": "P4",
      },
      finalPlayers: [
        {
          playerId: "boss-1",
          label: "P1",
          role: "boss",
          hp: 100,
          gold: 0,
          remainingLives: 1,
          eliminated: false,
          rank: 1,
          selectedHeroId: "",
          selectedBossId: "remilia",
          totalGoldEarned: 0,
          totalGoldSpent: 0,
          purchaseCount: 0,
          refreshCount: 0,
          sellCount: 0,
          boardUnits: [],
        },
      ],
      battles: [{
        leftPlayerId: "raid-a",
        rightPlayerId: "boss-1",
        winner: "right",
        bossSurvivors: 1,
        raidSurvivors: 1,
        unitDamageBreakdown: [],
        unitOutcomes: [
          {
            playerId: "raid-a",
            label: "P2",
            unitId: "jyoon",
            unitName: "女苑",
            side: "raid",
            totalDamage: 18,
            phaseContributionDamage: 18,
            finalHp: 560,
            alive: true,
            unitLevel: 1,
            subUnitName: "",
            isSpecialUnit: true,
            attackCount: 1,
            hitCount: 1,
            moveCount: 2,
            firstAttackAtMs: 1800,
            firstReachedAttackRangeAtMs: 1500,
            lifetimeMs: 3000,
            battleDurationMs: 3000,
            plannedApproachMoveSampleCount: 1,
            contestedPursuitMoveSampleCount: 1,
            sharedPursuitMoveSampleCount: 1,
            plannedApproachReachedRangeWithoutAttackWhileTargetAliveCount: 0,
            plannedApproachNoReachNoAttackWhileTargetAliveCount: 0,
          },
          {
            playerId: "raid-b",
            label: "P3",
            unitId: "reimu",
            unitName: "霊夢",
            side: "raid",
            totalDamage: 40,
            phaseContributionDamage: 40,
            finalHp: 0,
            alive: false,
            unitLevel: 1,
            subUnitName: "",
            isSpecialUnit: true,
            attackCount: 1,
            hitCount: 1,
            moveCount: 1,
            firstAttackAtMs: 2500,
            firstReachedAttackRangeAtMs: 2100,
            lifetimeMs: 2600,
            battleDurationMs: 3000,
            plannedApproachMoveSampleCount: 1,
            contestedPursuitMoveSampleCount: 0,
            sharedPursuitMoveSampleCount: 1,
            plannedApproachReachedRangeWithoutAttackWhileTargetAliveCount: 0,
            plannedApproachNoReachNoAttackWhileTargetAliveCount: 0,
          },
        ],
      }],
    }]);

    expect(aggregate.raidSpecialMeleeUnitDiagnostics).toEqual([
      {
        unitId: "jyoon",
        unitName: "女苑",
        battleAppearances: 1,
        averageDamagePerBattle: 18,
        averageAttackCountPerBattle: 1,
        averageFirstAttackMs: 1800,
        firstAttackSamples: 1,
        averageFirstReachedAttackRangeAtMs: 1500,
        firstReachedAttackRangeSamples: 1,
        noAttackWithoutReachingRangeBattleRate: 0,
        noAttackDespiteReachingRangeBattleRate: 0,
        contestedPursuitMoveRate: 1,
        sharedPursuitMoveSampleCount: 1,
        zeroDamageBattleRate: 0,
        survivalRate: 1,
      },
    ]);
  });

  test("aggregates lateral drift and shared pursuit contention diagnostics", () => {
    const aggregate = buildBotOnlyBaselineAggregateReport([{
      totalRounds: 1,
      bossPlayerId: "boss-1",
      ranking: ["boss-1", "raid-a", "raid-b", "raid-c"],
      playerLabels: {
        "boss-1": "P1",
        "raid-a": "P2",
        "raid-b": "P3",
        "raid-c": "P4",
      },
      finalPlayers: [],
      battles: [{
        leftPlayerId: "boss-1",
        rightPlayerId: "raid-a",
        winner: "left",
        unitDamageBreakdown: [],
        unitOutcomes: [
          {
            playerId: "raid-a",
            label: "P2",
            unitId: "yoshika",
            unitName: "宮古芳香",
            unitType: "yoshika",
            side: "raid",
            totalDamage: 0,
            phaseContributionDamage: 0,
            finalHp: 100,
            alive: true,
            unitLevel: 1,
            subUnitName: "",
            isSpecialUnit: false,
            attackCount: 0,
            hitCount: 0,
            damageTaken: 0,
            moveCount: 2,
            firstMoveAtMs: 0,
            firstAttackAtMs: null,
            repositionMoveCount: 0,
            lifetimeMs: 300,
            battleDurationMs: 300,
            initialNearestEnemyDistance: 3,
            bestNearestEnemyDistance: 2,
            lateralLeftMoveCount: 2,
            lateralRightMoveCount: 0,
            firstLateralMoveDirection: "left",
            sharedPursuitMoveSampleCount: 2,
            contestedPursuitMoveSampleCount: 2,
          },
          {
            playerId: "raid-b",
            label: "P3",
            unitId: "rin",
            unitName: "火焔猫燐",
            unitType: "rin",
            side: "raid",
            totalDamage: 20,
            phaseContributionDamage: 0,
            finalHp: 100,
            alive: true,
            unitLevel: 1,
            subUnitName: "",
            isSpecialUnit: false,
            attackCount: 1,
            hitCount: 1,
            damageTaken: 0,
            moveCount: 1,
            firstMoveAtMs: 0,
            firstAttackAtMs: 200,
            repositionMoveCount: 0,
            lifetimeMs: 300,
            battleDurationMs: 300,
            initialNearestEnemyDistance: 3,
            bestNearestEnemyDistance: 1,
            lateralLeftMoveCount: 1,
            lateralRightMoveCount: 0,
            firstLateralMoveDirection: "left",
            sharedPursuitMoveSampleCount: 1,
            contestedPursuitMoveSampleCount: 0,
          },
        ],
      }],
    }]);

    expect(aggregate.rangeActionDiagnosticsMetrics).toEqual([
      expect.objectContaining({
        side: "raid",
        rangeBand: "range_1",
        battleAppearances: 2,
        averageLeftLateralMovesPerBattle: 1.5,
        averageRightLateralMovesPerBattle: 0,
        firstLateralMoveLeftRate: 1,
        firstLateralMoveRightRate: 0,
        firstLateralMoveSamples: 2,
        sharedPursuitMoveSampleCount: 3,
        contestedPursuitMoveRate: 2 / 3,
        plannedApproachGroupMoveSampleCount: 0,
        averagePlannedApproachGroupCompetitorCount: null,
        averagePlannedApproachGroupAssignedCount: null,
        oversubscribedPlannedApproachGroupRate: null,
        plannedApproachBattleCount: 0,
        plannedApproachMoveSampleCount: 0,
        plannedApproachStillOpenRate: null,
        usedPlannedApproachRate: null,
        plannedApproachPathBlockedRate: null,
        plannedApproachFirstAttackRate: null,
        plannedApproachMatchedFirstAttackTargetRate: null,
        plannedApproachReachedRangeWithoutAttackRate: null,
        plannedApproachNoReachNoAttackRate: null,
      }),
    ]);
  });
});
